### ISSUE TITLE
Bug in ZFS logs volume type

### ISSUE THREAD

**Issue by artiomn** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#61]
```
Ошибка #0:
Exception: raidz1: Logs can only be mirror or plain in /usr/share/omvzfs/Zpool.php:622
Stack trace:
#0 /usr/share/omvzfs/Zpool.php(529): OMVModuleZFSZpool->output('logs', 'raidz1', 'mirror-1 dm-nam...')
#1 /usr/share/omvzfs/Zpool.php(91): OMVModuleZFSZpool->assemblePool('tank0')
#2 /usr/share/omvzfs/Utils.php(275): OMVModuleZFSZpool->__construct('tank0')
#3 /usr/share/openmediavault/engined/rpc/zfs.inc(180): OMVModuleZFSUtil::getZFSFlatArray()
#4 [internal function]: OMVRpcServiceZFS->getObjectTree(Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#6 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getObjectTree', Array, Array)
#7 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ZFS', 'getObjectTree', Array, Array, 1)
#8 {main}
```

Why?

**Comment by ryecoaaron** [comment]
Closing due to age.
