### ISSUE TITLE
Invalid RPC response in OMV5

### ISSUE THREAD

**Issue by ooZberg** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#69]
Invalid RPC response error message is shown when clicking Storage -> ZFS in web interface
```
Error #0:
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('ZFS', 'getObjectTree', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}
```

And the syslog shows
```
Apr 29 22:22:25 server-name omv-engined[29898]: PHP Fatal error: Uncaught Error: Call to a member function getImpl() on null in /usr/share/php/openmediavault/system/filesystem/filesystem.inc:902
Apr 29 22:22:25 server-name omv-engined[29898]: Stack trace:
Apr 29 22:22:25 server-name omv-engined[29898]: #0 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(158): OMV\System\Filesystem\Filesystem::getImplByMountPoint('/storage')
Apr 29 22:22:25 server-name omv-engined[29898]: #1 [internal function]: Engined\Rpc\ShareMgmt->enumerateSharedFolders(Array, Array)
Apr 29 22:22:25 server-name omv-engined[29898]: #2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
Apr 29 22:22:25 server-name omv-engined[29898]: #3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('enumerateShared...', Array, Array)
Apr 29 22:22:25 server-name omv-engined[29898]: #4 /usr/share/omvzfs/Utils.php(226): OMV\Rpc\Rpc::call('ShareMgmt', 'enumerateShared...', Array, Array)
Apr 29 22:22:25 server-name omv-engined[29898]: #5 /usr/share/openmediavault/engined/rpc/zfs.inc(186): OMVModuleZFSUtil::fixOMVMntEnt(Array)
Apr 29 22:22:25 server-name omv-engined[29898]: #6 [internal function]: OMVRpcServiceZFS->getObjectTree(Array, Array)
Apr 29 22:22:25 server-name omv-engined[29898]: #7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
Apr 29 22:22:25 server-name omv-engined[29898]: #8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod in /usr/share/php/openmediavault/system/filesystem/filesystem.inc on line 902
(END)
```

Installed versions
```
openmediavault-omvextrasorg/buster,now 5.3.1 all [installed]
openmediavault-zfs/buster,now 5.0.5 amd64 [installed]
openmediavault/usul,now 5.4.2-1 all [installed]
```

For the record, the zfs pool contains multiple volumes mounted on top of each other, like this
```
tank/storage              424G   190G    21K  /storage
tank/storage/vol1         91.0G  190G  75.1G  /storage/vol1
tank/storage/vol2         333G   190G  46.5G  /storage/vol2
...
```

And this used to work fine in OMV4, but after upgrading to OMV5 it sopped working.

**Comment by ryecoaaron** [comment]
Did you clear your browser cache?

**Comment by ooZberg** [comment]
I have tried different browsers and incognito mode so I am pretty sure it is not a browser cache issue. I have also restarted the server a few times without any difference.

**Comment by ryecoaaron** [comment]
Closing due to age and OMV 5 is not supported anymore.
